name: Deploy Game

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build project
        run: yarn build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Deploy to A.D.S. Games
        if: startsWith(github.ref, 'refs/tags/v')
        uses: adsgames/deploy-to-adsgames@v1.1.2
        with:
          project-id: gameoflife
          build-dir: ./dist/
          platform: WEB
          bucket-access-key: ${{ secrets.LINODE_BUCKET_ACCESS_KEY }}
          bucket-secret-key: ${{ secrets.LINODE_BUCKET_SECRET_KEY }}
          api-key: ${{ secrets.ADSGAMES_API_KEY }}
